In [2]:
import sys, os
# sys.path.append('../python')

from util import *


In [3]:
ticker_dict, tickerSymbols = get_categorical_tickers()
start="2010-01-01"
end="2019-12-31"

In [4]:

tickeranalysis = tickerSymbols[0]
LSTM_1 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0, naive = True)
LSTM_1.full_workflow_and_plot()
plt.clf()
LSTM_1.plot_bot_decision()
plt.clf()
plt.show()

[*********************100%***********************]  1 of 1 completed
1/1 [==============================] - 0s 10ms/step


KeyboardInterrupt: 

In [6]:
LSTM_2 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0)
LSTM_2.full_workflow_and_plot()
plt.clf()
LSTM_2.plot_bot_decision()
plt.clf()
# LSTM_3 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 1)
# LSTM_3.full_workflow_and_plot()
# plt.clf()
# LSTM_3.plot_bot_decision()
# plt.clf()

[*********************100%***********************]  1 of 1 completed
1/1 [==============================] - 0s 48ms/step


1/1 [==============================] - 0s 28ms/step


1/1 [==============================] - 0s 16ms/step
You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.
The relative test RMS error is 0.004568
The relative test MAE is 0.050048
The relative test RMS error for the updated dataset is 0.005031
The relative train RMS error is 0.001158
The relative train MAE is 0.025352
The relative train RMS error for the updated dataset is 0.003547


<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [ ]:
tickeranalysis = tickerSymbols[1]
LSTM_4 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0, naive = True)
LSTM_4.full_workflow_and_plot()
plt.clf()
LSTM_4.plot_bot_decision()
plt.clf()
LSTM_5 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0)
LSTM_5.full_workflow_and_plot()
plt.clf()
LSTM_5.plot_bot_decision()
plt.clf()
LSTM_6 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 1)
LSTM_6.full_workflow_and_plot()
plt.clf()
LSTM_6.plot_bot_decision()
plt.clf()

[*********************100%***********************]  1 of 1 completed
1/1 [==============================] - 0s 34ms/step


1/1 [==============================] - 0s 22ms/step


1/1 [==============================] - 0s 24ms/step
You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.
The relative test RMS error is 0.008918
The relative test MAE is 0.071325
The relative test RMS error for the updated dataset is 0.005513
The relative train RMS error is 0.001234
The relative train MAE is 0.023560
The relative train RMS error for the updated dataset is 0.005178
[*********************100%***********************]  1 of 1 completed
1/1 [==============================] - 0s 20ms/step


1/1 [==============================] - 0s 31ms/step


1/1 [==============================] - 0s 34ms/step


In [ ]:
tickeranalysis = tickerSymbols[2]
LSTM_7 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0, naive = True)
LSTM_7.full_workflow_and_plot()
plt.clf()
LSTM_7.plot_bot_decision()
plt.clf()
LSTM_8 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 0)
LSTM_8.full_workflow_and_plot()
plt.clf()
LSTM_8.plot_bot_decision()
plt.clf()
LSTM_9 = LSTM_Model(tickerSymbol = tickeranalysis, start = start, end = end, depth = 1)
LSTM_9.full_workflow_and_plot()
plt.clf()
LSTM_9.plot_bot_decision()
plt.clf()
plt.show()

In [22]:
import yfinance as yf

ticker_dict, tickerSymbols = get_categorical_tickers()
start="2010-01-01"
end="2019-12-31"

tickerData = yf.Ticker(tickerSymbols[0])
tickerData
tickerDf = yf.download(tickerSymbols[0], start=start, end=end)
# tickerDf.head(15)
y = tickerDf['Adj Close'].values
tSize = int(y.size*.8)
m=y.mean()
s=y.std()

y = (y - m) / s
y
data_preprocess(y,0,tSize,60,1)


[*********************100%***********************]  1 of 1 completed
(60, 1)
[[[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]

 [[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]

 [[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]

 ...

 [[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]

 [[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]

 [[-1.46035859]
  [-1.45880121]
  [-1.4568191 ]
  ...
  [-1.14339043]
  [-1.13472576]
  [-1.13672203]]]


In [21]:

def data_preprocess(dataset, iStart, iEnd, sHistory, forward_look=1):
        '''
        Preprocess the data to make either the test set or the train set
        :param dataset: np.array of time-series data
        :param iStart: int of index start
        :param iEnd: int of index end
        :param sHistory: int number of days in history that we need to look at
        :param forward_look: int of number of days in the future that needs to predicted
        :return: returns a list of test/train data
        '''
        data = []
        target = []
        iStart += sHistory
        if iEnd is None:
            iEnd = len(dataset) - forward_look + 1
        for i in range(iStart, iEnd):
            indices = range(i - sHistory, i)  # set the order
            if forward_look > 1:
                fwd_ind = range(i, i + forward_look)
                fwd_entity = np.asarray([])
                fwd_entity = np.append(fwd_entity, dataset[fwd_ind])
            reshape_entity = np.asarray([])
            reshape_entity = np.append(reshape_entity, dataset[0:60]) 
            # Comment this out if there are multiple identifiers in the feature vector
            data.append(np.reshape(reshape_entity, (sHistory, 1)))  #
            if forward_look > 1:
                target.append(np.reshape(fwd_entity, (forward_look, 1)))
            else:
                target.append(dataset[i])
        data = np.array(data)
        target = np.array(target)
        print(data.shape[-2:])
        print(data)
#         print(target)